language: node_js
node_js: 
  - "8"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database hellobookstest;' -U postgres

after_success:
 - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage