language: node_js
node_js: 
  - "8"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database hellobookstest;' -U postgres

after_success:
 - npm run coverage